# Generated by Django 2.2.12 on 2020-07-09 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('size_price', models.CharField(max_length=100, verbose_name='サイズ価格')),
                ('flavor_title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('flavor_title_2', models.CharField(max_length=100, verbose_name='フレーバー2')),
                ('option_title', models.CharField(max_length=100, verbose_name='オプション')),
                ('option_price', models.CharField(max_length=100, verbose_name='オプション価格')),
                ('option_title_2', models.CharField(max_length=100, verbose_name='オプション2')),
                ('option_price_2', models.CharField(max_length=100, verbose_name='オプション2価格')),
                ('total_price', models.IntegerField(default=0, verbose_name='合計')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='オプション')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('furigana', models.CharField(max_length=30, verbose_name='フリガナ')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=13, verbose_name='電話番号')),
                ('receipt', models.CharField(max_length=30, verbose_name='受取日時')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文受付日')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Cart', verbose_name='予約注文商品')),
            ],
        ),
    ]
