# Generated by Django 2.2.12 on 2020-07-10 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('is_active', models.BooleanField(default=True, help_text='このフレーバーを掲載するかを指定します。 選択を解除すると非表示になります。', verbose_name='掲載判定')),
            ],
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='オプション')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='SizeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('flavor_item', models.ManyToManyField(to='app.FlavorItem')),
                ('option_item', models.ManyToManyField(to='app.OptionItem')),
                ('size_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SizeItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='app.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
