# Generated by Django 2.2.12 on 2020-07-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('is_active', models.BooleanField(default=True, help_text='このフレーバーを掲載するかを指定します。 選択を解除すると非表示になります。', verbose_name='掲載判定')),
            ],
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='オプション')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='SizeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('furigana', models.CharField(max_length=30, verbose_name='フリガナ')),
                ('email', models.EmailField(max_length=256, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=13, verbose_name='電話番号')),
                ('receipt', models.CharField(max_length=30, verbose_name='受取日時')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文受付日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='注文完了')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='注文時刻')),
                ('size_title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('size_price', models.IntegerField(verbose_name='サイズ価格')),
                ('flavor_title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('flavor_price', models.IntegerField(default=0, verbose_name='フレーバー価格')),
                ('flavor2_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='フレーバー2')),
                ('flavor2_price', models.IntegerField(default=0, verbose_name='フレーバー2価格')),
                ('option_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='オプション')),
                ('option_price', models.IntegerField(default=0, verbose_name='オプション価格')),
                ('option2_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='オプション2')),
                ('option2_price', models.IntegerField(default=0, verbose_name='オプション2価格')),
                ('option3_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='オプション3')),
                ('option3_price', models.IntegerField(default=0, verbose_name='オプション3価格')),
                ('total_price', models.IntegerField(verbose_name='合計')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
