# Generated by Django 2.2.12 on 2020-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='メールアドレス'),
        ),
    ]
