# Generated by Django 2.2.12 on 2020-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='注文時刻'),
        ),
    ]
