# Generated by Django 2.2.12 on 2020-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=13, verbose_name='電話番号')),
                ('receipt', models.DateTimeField(verbose_name='受取日時')),
            ],
        ),
    ]
