# Generated by Django 2.2.12 on 2020-07-08 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('furigana', models.CharField(max_length=30, verbose_name='フリガナ')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=13, verbose_name='電話番号')),
                ('receipt', models.DateTimeField(verbose_name='受取日時')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文受付日')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderUser',
        ),
    ]
