# Generated by Django 2.2.12 on 2020-07-10 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200711_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文時刻'),
        ),
    ]
