# Generated by Django 2.2.12 on 2020-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200711_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='合計'),
        ),
    ]
