# Generated by Django 2.2.12 on 2020-06-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
