# Generated by Django 2.2.12 on 2020-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200604_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('1', 'ミニサイズ'), ('2', 'シングルサイズ'), ('3', 'ダブルサイズ')], max_length=10, verbose_name='サイズ')),
            ],
        ),
    ]
