# Generated by Django 2.2.12 on 2020-06-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ミニサイズ', 'ミニサイズ'), ('シングルサイズ', 'シングルサイズ'), ('ダブルサイズ', 'ダブルサイズ')], max_length=10, verbose_name='サイズ')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
