# Generated by Django 2.2.12 on 2020-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200715_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0, verbose_name='注文番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_day',
            field=models.IntegerField(default=0, verbose_name='注文日'),
        ),
    ]
