# Generated by Django 2.2.12 on 2020-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200622_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=10, verbose_name='サイズ'),
        ),
    ]
