# Generated by Django 2.2.12 on 2020-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200716_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(verbose_name='注文番号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_day',
            field=models.IntegerField(verbose_name='注文日'),
        ),
    ]
