# Generated by Django 2.2.12 on 2020-07-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200716_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_day',
            field=models.IntegerField(verbose_name='注文受取日'),
        ),
    ]
