# Generated by Django 2.2.12 on 2020-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200624_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='フレーバー名')),
                ('price', models.IntegerField(null=True, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='オプション名')),
                ('price', models.IntegerField(null=True, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=100, verbose_name='サイズ'),
        ),
    ]
