# Generated by Django 2.2.12 on 2020-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_whatsnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='comment',
            field=models.CharField(help_text='※45文字以内で入力してください。', max_length=45, verbose_name='コメント'),
        ),
    ]
