# Generated by Django 2.2.12 on 2020-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200627_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(max_length=100, verbose_name='サイズ')),
                ('size_price', models.IntegerField(verbose_name='サイズ価格')),
                ('flavor_title', models.CharField(max_length=100, verbose_name='フレーバー')),
                ('flavor_title_2', models.CharField(max_length=100, verbose_name='フレーバー2')),
                ('option_title', models.CharField(max_length=100, verbose_name='オプション')),
                ('option_price', models.IntegerField(verbose_name='オプション価格')),
                ('option_title_2', models.CharField(max_length=100, verbose_name='オプション2')),
                ('option_price_2', models.IntegerField(verbose_name='オプション2価格')),
            ],
        ),
        migrations.AlterField(
            model_name='flavor',
            name='price',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
    ]
