# Generated by Django 2.2.12 on 2020-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200718_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('e_name', models.CharField(max_length=100, verbose_name='英語名称')),
                ('j_name', models.CharField(max_length=100, verbose_name='日本語名称')),
                ('m_price', models.IntegerField(verbose_name='ミニ価格')),
                ('s_price', models.IntegerField(verbose_name='シングル価格')),
                ('w_price', models.IntegerField(verbose_name='ダブル価格')),
                ('comment', models.CharField(help_text='※100文字以内で入力してください。', max_length=100, verbose_name='コメント')),
            ],
        ),
    ]
