# Generated by Django 2.2.12 on 2020-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200627_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='option_price',
            field=models.CharField(max_length=100, verbose_name='オプション価格'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='option_price_2',
            field=models.CharField(max_length=100, verbose_name='オプション2価格'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size_price',
            field=models.CharField(max_length=100, verbose_name='サイズ価格'),
        ),
    ]
