# Generated by Django 2.2.12 on 2020-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='comment',
            field=models.TextField(help_text='※100文字以内で入力してください。', max_length=100, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='whatsnew',
            name='comment',
            field=models.TextField(help_text='※45文字以内で入力してください。', max_length=45, verbose_name='コメント'),
        ),
    ]
