# Generated by Django 2.2.12 on 2020-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200627_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, max_length=100, verbose_name='合計'),
        ),
    ]
