# Generated by Django 2.2.12 on 2020-07-18 01:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200718_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images', verbose_name='画像'),
        ),
    ]
