# Generated by Django 2.2.12 on 2020-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200720_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='オプション4画像'),
        ),
        migrations.AddField(
            model_name='cart',
            name='option4_price',
            field=models.IntegerField(default=0, verbose_name='オプション4価格'),
        ),
        migrations.AddField(
            model_name='cart',
            name='option4_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='オプション4'),
        ),
    ]
