# Generated by Django 2.2.12 on 2020-08-02 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200722_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='クーポン使用日'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.IntegerField(default=0, verbose_name='クーポン金額'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_use',
            field=models.BooleanField(default=False, verbose_name='クーポン利用'),
        ),
    ]
