# Generated by Django 3.1.8 on 2021-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200811_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート', 'verbose_name_plural': 'カート'},
        ),
        migrations.AlterModelOptions(
            name='flavoritem',
            options={'verbose_name': '【STEP2】フレーバー', 'verbose_name_plural': '【STEP2】フレーバー'},
        ),
        migrations.AlterModelOptions(
            name='optionitem',
            options={'verbose_name': '【STEP3】オプション', 'verbose_name_plural': '【STEP3】オプション'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文一覧', 'verbose_name_plural': '注文一覧'},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={'verbose_name': 'おすすめ商品', 'verbose_name_plural': 'おすすめ商品'},
        ),
        migrations.AlterModelOptions(
            name='sizeitem',
            options={'verbose_name': '【STEP1】サイズ', 'verbose_name_plural': '【STEP1】サイズ'},
        ),
        migrations.AlterModelOptions(
            name='todayorder',
            options={'verbose_name': '当日注文の可否', 'verbose_name_plural': '当日注文の可否'},
        ),
        migrations.AlterModelOptions(
            name='whatsnew',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ'},
        ),
        migrations.AddField(
            model_name='flavoritem',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AddField(
            model_name='flavoritem',
            name='web_only',
            field=models.BooleanField(default=False, verbose_name='WEB限定'),
        ),
    ]
