# Generated by Django 2.2.12 on 2020-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '女性'), ('2', '男性')], max_length=2, null=True, verbose_name='性別'),
        ),
    ]
