# Generated by Django 2.2.12 on 2020-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200702_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='このユーザーをアクティブとして扱うかどうかを指定します。 アカウントを削除する代わりに、これを選択解除します。', verbose_name='アクティブ判定'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='ユーザーがこの管理サイトにログインできるかどうかを指定します。', verbose_name='管理サイト使用権限'),
        ),
    ]
