# Generated by Django 3.1.8 on 2021-04-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200726_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '会員一覧', 'verbose_name_plural': '会員一覧'},
        ),
    ]
