# Generated by Django 2.2.12 on 2020-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200704_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='このユーザーをアクティブとして扱うかどうかを指定します。 アカウントを削除する代わりに、これを選択解除します。', verbose_name='アクティブ判定'),
        ),
    ]
