# Generated by Django 2.2.12 on 2020-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200705_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='このユーザーをアクティブとして扱うかどうかを指定します。 アカウントを削除する代わりに、これを選択解除します。', verbose_name='アクティブ判定'),
        ),
    ]
